config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'
  get 'access/unauthorized'

  resources :users do
      member do
          get :delete
          get :manage
          patch :manage_update
        end
      end

  # get all the urls, including delete
  resources :items do
    member do
      get :delete
    end
  end

# add new views before others so they are parsed and routed properly
  get 'transactions/checkout', to:'transactions#checkout'
  post 'transactions/submit'
  get 'transactions/showAllUserItems'

  resources :transactions do
   member do
     get :delete
   end
  end
  #Manual so it recognizes new views
  #get 'transactions', to: 'transactions#index'
  #get 'transactions/show'
  #get 'transactions/new'
  #get 'transactions/edit'
  #get 'transactions/delete'

  resources :log, only: [:index]
  
  get 'users/key', to: 'users#will_checkout_or_return_key'
  post 'users/key', to: 'users#checkout_or_return_key'

  #get 'items/index'
  #get 'items/show'
  #get 'items/new'
  #get 'items/edit'
  #get 'items/delete'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    
    has_secure_password
    
    EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i
    
    
    validates :first_name, :presence => true,
                                                   :length => { :maximum => 25 }
    validates :last_name, :presence => true,
                          :length => { :maximum => 50 }
    validates :email, :presence => true,
                      :length => { :maximum => 100 },
                      :format => EMAIL_REGEX,
                      :confirmation => true,
                      :uniqueness => true

    
    scope :sorted, lambda { order('last_name ASC, first_name ASC')}

    def name
      "#{first_name} #{last_name}"
      # Or: first_name + ' ' + last_name
      # Or: [first_name, last_name].join(' ')
    end
    
    has_many :checkouts
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :confirmed_logged_in, :except => [:new, :create]
  before_action :user_is_admin, :except => [:new, :create,:will_checkout_or_return_key, :checkout_or_return_key]
  layout :get_user_layout, :except => [:new, :create]

  def index
    @users = User.all
    if ((params[:search_tag] != nil) && (params[:search_tag] != ""))
      @users_first_name = User.where(first_name: params[:search_tag])
      @users_last_name = User.where(last_name: params[:search_tag])
      @users_permissions = User.where(permissions: params[:search_tag])
      @users_sorted = [].concat(@users_first_name).concat(@users_last_name).concat(@users_permissions)
      @users_sorted = @users_sorted.uniq
    elsif (params[:sort_type] != nil)
        @sort_type = params[:sort_type]
        @sort_dir = params[:sort_dir]
        if @sort_type == 'First Name'
          @users_sorted = @users.sort_by { |user| user.first_name }
        elsif @sort_type == 'Last Name'
          @users_sorted = @users.sort_by { |user| user.last_name }
        elsif @sort_type == 'Permissions'
          @users_sorted = @users.sort_by { |user| user.permissions }
        elsif @sort_type == 'Amount of Rented Items'
          @users_sorted = @users.sort_by { |user| user.item_ids.length }
        elsif @sort_type == 'Has Key'
          @users_sorted = @users.sort_by { |user| user.hasKey }
        end

        if @sort_dir == 'Z -> A'
          @users_sorted = @users_sorted.reverse
        end

    else
        @sort_type = 'First Name'
        @sort_dir = 'A -> Z'
        @users_sorted = @users.sort_by { |user| user.first_name }
    end
  end

  def new
      @user = User.new
  end

  def create
    @admins = User.where(:permissions=>2)
    @user = User.new(user_params)
    if @user.save
      UserMailer.with(user: @user).welcome_email.deliver_now
      @admins.each do |admin|
        UserMailer.with(user: @user, admin: admin).admin_approval_email.deliver_now
      end
      flash[:notice] = 'Account Created. You will receive an e-mail shortly. Please await authorization before using the site.'
      redirect_to(access_login_path)
    else
      render('new')
    end
  end

  def edit
      @user = User.find(params[:id])
  end

  def show
      @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @perm = @user.permissions
    if User.sum(:hasKey) < 2 or user_params[:hasKey] == "0"
      if @user.update_attributes(user_params)
        if @user.permissions > @perm
          UserMailer.with(user: @user).authorized_email.deliver_now
          redirect_to(users_path)
        else
        redirect_to(user_path(@user))
        end
      else
        render('edit')
      end
    else
      flash[:notice] = "Sorry, there are no keys available to checkout."
      render('edit')
    end
  end

  def delete
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to(users_path)
  end

  def will_checkout_or_return_key
    @user = User.find_by_id(session[:user_id])
  end

  def checkout_or_return_key
    @user = User.find_by_id(session[:user_id])
    #@user = User.find(params[:id])
    if params[:commit] == 'Checkout Key'
      if @user.hasKey == 0 and User.sum(:hasKey) < 2
        User.update(session[:user_id], :hasKey => 1)
      elsif @user.hasKey == 1
        flash[:notice] = "You already have a key checked out!"
      elsif User.sum(:hasKey) > 1
        flash[:notice] = "Sorry, there are no keys available to checkout."
      end
    end
  end

  def manage
    @user = User.find_by_id(session[:user_id])
  end

  def manage_update
    @user = User.find_by_id(session[:user_id])
    if @user.update_attributes(user_params)
      redirect_to(access_menu_path)
    end
  end

  private

  def user_params
    # Permit :password, but NOT :password_digest
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :permissions,
      :password,
      :hasKey
    )
  end

  def get_user_layout
    permissions = User.find(session[:user_id]).permissions
    if permissions == 2
        "admin"
    elsif permissions == 1
        "user"
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/delete.html.erb
<div class="container-fluid">

  <div class = "top-button">
    <button type="button"><%= link_to("Back to User Page", user_path(@user), :class => 'back-link') %></button>
  </div>

  <div class="row">
    <div class="col" align="center">
      <div class="Titles">
        Delete User
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col" align="center">
      <div class="card" style="margin-top:2%; width:50%; margin-left:0%;" align="center">
        <div class="card-body">
          <%= form_for(@user, :method => 'delete') do |f| %>
          <h1><%= f.object.first_name %> <%= f.object.last_name %></h1>
          <p>Are you sure you want to delete this user?</p>
          <div class="form-buttons">
            <%= f.submit("Submit") %>
           </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/users/edit.html.erb
<div class="top-button">
  <button type="button"><%= link_to("Back to User Page", user_path(@user), :class => 'back-link') %></button>
</div>

<div class = "container">
  
  <div class="row">
  <div class="col" align="center">
    <div class="Titles">
      Edit User
    </div>
  </div>
  </div>

  <%= form_for(@user) do |f| %>

  <table class="table" summary = "user form fields">
    <tr>
      <th>First Name</th>
      <td><%= f.text_field(:first_name) %></td>
    </tr>
    <tr>
      <th>Last Name</th>
      <td><%= f.text_field(:last_name) %></td>
    </tr>
    <tr>
      <th>Email</th>
      <td><%= f.text_field(:email) %></td>
    </tr>
    <tr>
      <th>Permission Level</th>
      <td><%= f.select :permissions, [0,1,2] %></td>
    </tr>
    <tr>
     <th>Key checked out</th>
     <td><%= f.select :hasKey, [ ["Yes", 1], ["No", 0]] %></td>
   </tr>
  </table>

  <div class="form-buttons" align="center">
    <%= f.submit("Submit") %>
  </div>

  <% end %>
</div>

app/views/users/index.html.erb
<div class = "container">

  <div class="row">
  <div class="col" align="center">
    <div class="Titles">
      User List
    </div>
  </div>
  </div>

  <%= link_to("Add New user", new_user_path, :class=> 'action new') %>

  <%= form_tag({:action => 'index'}, :method => :get) do %>
    <p>Sort By: <%= select_tag "sort_type", options_for_select(['First Name', 'Last Name',
      'Permissions', 'Amount of Rented Items', 'Has Key'], @sort_type)%>
      <%= select_tag "sort_dir", options_for_select(['A -> Z', 'Z -> A'], @sort_dir)%>
      <%= submit_tag("Sort") %>
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      <%= text_field_tag "search_tag"%>
      <%= submit_tag("Search") %></p>
  <% end %>

  <div class="row">
    <div class="col">
      <div class="card" style="margin-top:2%; width:100%; margin-left:0%;" align="center">
        <div class="card-body">
        <table class = "table" summary="user List">
        <tr class = "header">
          <th style="padding:0 15px 0 0;">First Name</th>
          <th style="padding:0 15px 0 0;">Last Name</th>
          <th style="padding:0 15px 0 0;">Permissions</th>
          <th style="padding:0 15px 0 0;">Amount of rented items</th>
          <th style="padding:0 15px 0 0;">Has Key</th>
          <th style="padding:0 15px 0 0;">Options</th>
          </tr>
        <% @users_sorted.each do |user| %>
        <tr>
          <td style="padding:0 15px 0 0;"><%= user.first_name %></td>
          <td style="padding:0 15px 0 0;"><%= user.last_name %></td>
          <td style="padding:0 15px 0 0;"><%= user.permissions %></td>
          <td style="padding:0 15px 0 0;"><%= user.item_ids.length %></td>
          <td style="padding:0 15px 0 0;"><%= user.hasKey == 0 ? 'No' : 'Yes' %></td>
          <td class="actions" style="padding:0 15px 0 0;">
            <button type="button" ><%= link_to("View Details", user_path(user), :class => 'action show') %></button>
            <button type="button" ><%= link_to("Show Items", {:controller => 'transactions', :action => "showAllUserItems", :id => user.id}) %></button>
          </td>
        </tr>
        <% end %>
        </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="top-button">
<button type="button"><%= link_to("Back to Users Page", users_path, :class => 'back-link') %></button>
</div>

<div class="container">

  <div class="row">
  <div class="col" align="center">
    <div class="Titles">
      New User
    </div>
  </div>
  </div>

<% if !!flash[:errors] %>
  <% flash[:errors].each do |e| %>
    <p style="color: red"><%= e %></p> <br>
  <% end %>
<% end %>
<%= form_for(@user) do |f| %>

    <table class="table">
      <tr>
        <th>First Name:</th>
        <td><%= f.text_field(:first_name)%></td>
      </tr>
      <tr>
        <th>Last Name:</th>
        <td><%= f.text_field(:last_name)%></td>
      </tr>
      <tr>
        <th>Email:</th>
        <td><%= f.text_field(:email)%></td>
      </tr>
      <tr>
        <th>Password:</th>
        <td><%= f.password_field(:password)%></td>
      </tr>

    </table>

<div class="form-buttons" align="center">
<%= f.submit("Submit") %>
</div>
<% end %>
</div>

app/views/users/show.html.erb
<div class="top-button">
  <button type="button"><%= link_to("Back to User List", users_path, :class => 'back-link') %></button>
</div>

<div class = "container">
  
  <div class="row">
  <div class="col" align="center">
    <div class="Titles">
      User Info
    </div>
  </div>
  </div>

  <table class="table" summary = "user form fields">
    <tr>
      <th>First Name</th>
      <td><%= @user.first_name %></td>
    </tr>
    <tr>
      <th>Last Name</th>
      <td><%= @user.last_name %></td>
    </tr>
    <tr>
      <th>Email</th>
      <td><%= @user.email %></td>
    </tr>
    <tr>
      <th>Permission Level</th>
      <td><%= @user.permissions %></td>
    </tr>
    <tr>
     <th>Key checked out</th>
     <td><%= @user.hasKey %></td>
   </tr>
  </table>

  <div class="form-buttons" align="center">
  <button><%= link_to("Edit user", edit_user_path(@user), :class => 'edit-link') %></button>
  <button><%= link_to("Delete user", delete_user_path(@user), :class => 'delete-link') %></button>
  </div>

</div>