config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'
  get 'access/unauthorized'

  resources :users do
      member do
          get :delete
          get :manage
          patch :manage_update
        end
      end

  # get all the urls, including delete
  resources :items do
    member do
      get :delete
    end
  end

# add new views before others so they are parsed and routed properly
  get 'transactions/checkout', to:'transactions#checkout'
  post 'transactions/submit'
  get 'transactions/showAllUserItems'

  resources :transactions do
   member do
     get :delete
   end
  end
  #Manual so it recognizes new views
  #get 'transactions', to: 'transactions#index'
  #get 'transactions/show'
  #get 'transactions/new'
  #get 'transactions/edit'
  #get 'transactions/delete'

  resources :log, only: [:index]
  
  get 'users/key', to: 'users#will_checkout_or_return_key'
  post 'users/key', to: 'users#checkout_or_return_key'

  #get 'items/index'
  #get 'items/show'
  #get 'items/new'
  #get 'items/edit'
  #get 'items/delete'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
    
  before_action :confirmed_logged_in, :except => [:login, :attempt_login, :logout]
  before_action :user_has_permissions, :except => [:unauthorized, :login, :attempt_login, :logout]

  def login
      
  end
  
  def attempt_login
    if params[:email].present? && params[:password].present?
        found_user = User.where(:email => params[:email]).first
        if found_user
            authorized_user = found_user.authenticate(params[:password])
        end
    end
      
    if authorized_user
        session[:user_id] = authorized_user.id
        if authorized_user.permissions > 0
            redirect_to(items_path)
        end
    else
        flash.now[:notice] = "Invalid username or password."
        render('login')
    end
  end
  
  def logout
    session[:user_id] = nil
    redirect_to(access_login_path)
  end

  def unauthorized
    @user = User.find_by_id(session[:user_id])
  end

  def get_user_layout
    permissions = User.find(session[:user_id]).permissions
    if permissions == 2
        "admin"
    elsif permissions == 1
        "user"
    end
  end


end

app/helpers/access_helper.rb
module AccessHelper
end

app/views/access/login.html.erb
<% @page_title = "Login" %>

<div class="container center-text">
  <%= form_tag(access_attempt_login_path, :method => :post) do %>
  <table>
    <tr>
      <td><%= label_tag(:email) %></td>
      <td><%= text_field_tag(:email, params[:email]) %></td>
    </tr>
    <tr>
      <td><%= label_tag(:password) %></td>
      <td><%= password_field_tag(:password) %></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td><%= submit_tag("Log In") %></td>
    </tr>
  </table>
  <% end %>
  <%= link_to("Register", new_user_path, :class => 'register-link') %>
</div>

app/views/access/unauthorized.html.erb
<% @page_title = "Unauthorized Account" %>

<div class="menu">
<h2>Please wait to be granted access by the administrator.</h2>
  <div class="identity">
  <p>Logged in as: <%= @user.first_name%> <%= @user.last_name%></p>
  </div>
    <ul>
        <li><%= link_to("Logout", access_logout_path) %></li>
    </ul>
</div>