config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'
  get 'access/unauthorized'

  resources :users do
      member do
          get :delete
          get :manage
          patch :manage_update
        end
      end

  # get all the urls, including delete
  resources :items do
    member do
      get :delete
    end
  end

# add new views before others so they are parsed and routed properly
  get 'transactions/checkout', to:'transactions#checkout'
  post 'transactions/submit'
  get 'transactions/showAllUserItems'

  resources :transactions do
   member do
     get :delete
   end
  end
  #Manual so it recognizes new views
  #get 'transactions', to: 'transactions#index'
  #get 'transactions/show'
  #get 'transactions/new'
  #get 'transactions/edit'
  #get 'transactions/delete'

  resources :log, only: [:index]
  
  get 'users/key', to: 'users#will_checkout_or_return_key'
  post 'users/key', to: 'users#checkout_or_return_key'

  #get 'items/index'
  #get 'items/show'
  #get 'items/new'
  #get 'items/edit'
  #get 'items/delete'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
    validates :name, :description, :total_stock, :avail_stock, :location, presence: {message: 'cannot be blank.'}
    validates :total_stock, :avail_stock, numericality: {only_integer: true, message: 'must be an integer.'}
    validates :total_stock, :avail_stock, numericality: {greater_than_or_equal_to: 0, message: 'must be nonnegative.'}
    validates :name, uniqueness: true, length: {maximum: 40, too_long: "is more than the maximum allowed (%{count} characters)."}
    validates :description, length: {maximum: 120, too_long: "is more than the maximum allowed (%{count} characters)."}
    validates :location, length: {maximum: 60, too_long: "is more than the maximum allowed (%{count} characters)."}
    validates :avail_stock, numericality: {less_than_or_equal_to: :total_stock, message: '(%{value}) must be less than total stock (%{count}).'}, unless: -> {total_stock.blank? || avail_stock.blank?}
    has_many :checkouts
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :confirmed_logged_in
  before_action :user_has_permissions
  layout :get_user_layout

  def index
    @items = Item.all
    if ((params[:search_tag] != nil) && (params[:search_tag] != ""))
      @items_name = Item.where(name: params[:search_tag])
      @items_desc = Item.where(description: params[:search_tag])
      @items_total = Item.where(total_stock: params[:search_tag])
      @items_avail = Item.where(avail_stock: params[:search_tag])
      @items_merch = Item.where(merch: params[:search_tag])
      @items_sorted = [].concat(@items_name)
                        .concat(@items_desc)
                        .concat(@items_total)
                        .concat(@items_avail)
                        .concat(@items_merch)
      @items_sorted = @items_sorted.uniq
      @items_sorted = @items_sorted.sort_by { |item| item.name }
    elsif (params[:sort_type] != nil)
      @sort_type = params[:sort_type]
      @sort_dir = params[:sort_dir]
      if @sort_type == 'Name'
        @items_sorted = @items.sort_by { |item| item.name }
      elsif @sort_type == 'Description'
        @items_sorted = @items.sort_by { |item| item.description }
      elsif @sort_type == 'Total Stock'
        @items_sorted = @items.sort_by { |item| item.total_stock }
      elsif @sort_type == 'Available Stock'
        @items_sorted = @items.sort_by { |item| item.avail_stock }
      elsif @sort_type == 'Merch'
        @items_sorted = @items.sort_by { |item| item.merch }
      end

      if @sort_dir == 'Z -> A'
        @items_sorted = @items_sorted.reverse
      end

    else
      @sort_type = 'Name'
      @sort_dir = 'A -> Z'
      @items_sorted = @items.sort_by { |item| item.name }
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(subject_params)
    if @item.save
      redirect_to(items_path)
    else
      out = ''
      @item.errors.full_messages.each do |msg|
        out = out + ' ' + msg
      end
      render('new')
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update_attributes(subject_params)
      redirect_to(item_path(@item))
    else
      out = ''
      @item.errors.full_messages.each do |msg|
        out = out + ' ' + msg
      end
      render('edit')
    end
  end

  def delete
    @item = Item.find(params[:id])
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to(items_path)
  end

  private

  def subject_params
    params.require(:item).permit(:name, :description, :total_stock, :avail_stock, :location, :merch)
  end

  def get_user_layout
    permissions = User.find(session[:user_id]).permissions
    if permissions == 2
        "admin"
    elsif permissions == 1
        "user"
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/delete.html.erb
<div class="container-fluid">

  <div class = "top-button">
    <button type="button"><%= link_to("Back to Item Page", item_path(@item), :class => 'back-link') %></button>
  </div>

  <div class="row">
    <div class="col" align="center">
      <div class="Titles">
        Delete Item
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col" align="center">
      <div class="card" style="margin-top:2%; width:50%; margin-left:0%;" align="center">
        <div class="card-body">
          <%= form_for(@item, :method => 'delete') do |f| %>
          <h1><%= f.object.name %></h1>
          <p>Are you sure you want to delete this item?</p>
          <div class="form-buttons">
            <%= f.submit("Submit") %>
           </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/items/edit.html.erb
<div class = "top-button">
  <button type="button"><%= link_to("Back to Item Page", item_path(@item), :class => 'back-link') %></button>
</div>

<div class = "container">

  <div class="row">
  <div class="col" align="center">
    <div class="Titles">
      Update Item
    </div>
  </div>
  </div>

  <%= form_for(@item) do |f| %>

  <table class="table" summary = "item form fields">
    <tr>
      <th>Item Name</th>
      <td><%= f.text_field(:name) %></td>
    </tr>
    <tr>
      <th>Description</th>
      <td><%= f.text_field(:description) %></td>
    </tr>
    <tr>
      <th>Total Stock</th>
      <td><%= f.text_field(:total_stock) %></td>
    </tr>
    <tr>
      <th>Available Stock</th>
      <td><%= f.text_field(:avail_stock) %></td>
    </tr>
    <tr>
      <th>Location</th>
      <td><%= f.text_field(:location) %></td>
    </tr>
    <tr>
      <th>Is this merchandise?</th>
      <td><%= f.select :merch, ['No', 'Yes'] %></td>
    </tr>
  </table>
  <div class="form-buttons" align="center">
  <%= f.submit("Submit") %>
  </div>
  <% end %>
</div>

app/views/items/index.html.erb
<div class = "container">

  <div class="row">
  <div class="col" align="center">
    <div class="Titles">
      Inventory
    </div>
  </div>
  </div>

  <%= link_to("Add New Item", new_item_path, :class=> 'action new') %>

  <%= form_tag({:action => 'index'}, :method => :get) do %>
    <p>Sort By: <%= select_tag "sort_type", options_for_select(['Name', 'Description',
      'Total Stock', 'Available Stock'], @sort_type)%>
      <%= select_tag "sort_dir", options_for_select(['A -> Z', 'Z -> A'], @sort_dir)%>
      <%= submit_tag("Sort") %>
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      <%= text_field_tag "search_tag"%>
      <%= submit_tag("Search") %></p>
  <% end %>

  <div class="row">
    <div class="col">
      <div class="card" style="margin-top:2%; width:100%; margin-left:0%;" align="center">
        <div class="card-body">
        <table class = "table" summary="item List">
        <tr class = "header">
          <th style="padding:0 15px 0 0;">Name</th>
          <th style="padding:0 15px 0 0;">Description</th>
          <th style="padding:0 15px 0 0;">Total Stock</th>
          <th style="padding:0 15px 0 0;">Available Stock</th>
          <th style="padding:0 15px 0 0;">Merch</th>
          <th style="padding:0 15px 0 0;">Options</th>
        </tr>
        <% @items_sorted.each do |item| %>
        <tr>
          <td style="padding:0 15px 0 0;"><%= item.name %></td>
          <td style="padding:0 15px 0 0;"><%= item.description %></td>
          <td style="padding:0 15px 0 0;"><%= item.total_stock %></td>
          <td style="padding:0 15px 0 0;"><%= item.avail_stock %></td>
          <td style="padding:0 15px 0 0;"><%= item.merch %></td>
          <td class="actions" style="padding:0 15px 0 0;">
            <button type="button" ><%= link_to("View Details", item_path(item), :class => 'action show') %></button>
            <button type="button" ><%= link_to("Checkout", {:controller => 'transactions', :action => 'checkout', :id => item.id}, :class => 'action edit') %></button>
          </td>
        </tr>
        <% end %>
        </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class= "top-button">
  <button type="button"><%= link_to("Back to Inventory Page", items_path, :class => 'back-link') %></button>
</div>

<div class = "container">

  <div class="row">
  <div class="col" align="center">
    <div class="Titles">
      Add Item
    </div>
  </div>
  </div>

  <%= form_for(@item) do |f| %>

  <table class="table" summary = "item form fields">
    <tr>
      <th>Item Name</th>
      <td><%= f.text_field(:name) %></td>
    </tr>
    <tr>
      <th>Description</th>
      <td><%= f.text_field(:description) %></td>
    </tr>
    <tr>
      <th>Total Stock</th>
      <td><%= f.text_field(:total_stock) %></td>
    </tr>
    <tr>
      <th>Available Stock</th>
      <td><%= f.text_field(:avail_stock) %></td>
    </tr>
    <tr>
      <th>Location</th>
      <td><%= f.text_field(:location) %></td>
    </tr>
    <tr>
      <th>Is this merchandise?</th>
      <td><%= f.select :merch, ['No', 'Yes'] %></td>
    </tr>
  </table>

  <div class="form-buttons" align="center">
    <%= f.submit("Submit") %>
  </div>

  <% end %>
</div>

app/views/items/show.html.erb
<div class="top-button">
  <button type="button"><%= link_to("Back to Inventory Page", items_path, :class => 'back-link') %></button>
</div>

<div class = "container">\

  <div class="row">
  <div class="col" align="center">
    <div class="Titles">
      Item Info
    </div>
  </div>
  </div>

  <table class="table" summary = "item details">
    <tr>
      <th>Name</th>
      <td><%= @item.name %></td>
    </tr>
    <tr>
      <th>Description</th>
      <td><%= @item.description %></td>
    </tr>
    <tr>
      <th>Total Stock</th>
      <td><%= @item.total_stock %></td>
    </tr>
    <tr>
      <th>Available Stock</th>
      <td><%= @item.avail_stock %></td>
    </tr>
    <tr>
        <th>Merchandise</th>
        <td><%= @item.merch %></td>
    </tr>
    <tr>
      <th>Location</th>
      <td><%= @item.location %></td>
    </tr>
  </table>

  <div class="form-buttons" align="center">
  <button><%= link_to("Edit item", edit_item_path(@item), :class => 'edit-link') %></button>
  <button><%= link_to("Delete item", delete_item_path(@item), :class => 'delete-link') %></button>
  </div>
</div>