config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'
  get 'access/unauthorized'

  resources :users do
      member do
          get :delete
          get :manage
          patch :manage_update
        end
      end

  # get all the urls, including delete
  resources :items do
    member do
      get :delete
    end
  end

# add new views before others so they are parsed and routed properly
  get 'transactions/checkout', to:'transactions#checkout'
  post 'transactions/submit'
  get 'transactions/showAllUserItems'

  resources :transactions do
   member do
     get :delete
   end
  end
  #Manual so it recognizes new views
  #get 'transactions', to: 'transactions#index'
  #get 'transactions/show'
  #get 'transactions/new'
  #get 'transactions/edit'
  #get 'transactions/delete'

  resources :log, only: [:index]
  
  get 'users/key', to: 'users#will_checkout_or_return_key'
  post 'users/key', to: 'users#checkout_or_return_key'

  #get 'items/index'
  #get 'items/show'
  #get 'items/new'
  #get 'items/edit'
  #get 'items/delete'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

# found article going over how to use regular expressions to validate email addresses entered into the form
# link to article: https://blog.mailtrap.io/rails-email-validation/
# more work can be done to better validate email addresses
REGEX_PATTERN = /^(.+)@(.+)$/.freeze

class TransactionsController < ApplicationController
#  before_action :authorize, only: %i[create edit update delete destroy show new index]
  layout :get_user_layout

  def index
    user = User.find(session[:user_id])
    if (user.permissions < 2)
      @transactions = Transaction.where(:requestor_email => user.email).sorted
      if ((params[:search_tag] != nil) && (params[:search_tag] != ""))
        @transactions_person = Transaction.where(requestor_name: params[:search_tag])
        @transactions_item = Transaction.where(item_name: params[:search_tag])
        @transactions_amount = Transaction.where(item_quantity: params[:search_tag])
        @transactions_event = Transaction.where(event: params[:search_tag])
        @transactions_created = Transaction.where(created_at: params[:search_tag])
        @transactions_status = Transaction.where(type_: params[:search_tag])
        @transactions_sorted = [].concat(@transactions_person)
                                  .concat(@transactions_item)
                                  .concat(@transactions_amount)
                                  .concat(@transactions_event)
                                  .concat(@transactions_created)
                                  .concat(@transactions_status)
        @transactions_sorted = @transactions_sorted.uniq
      elsif (params[:sort_type] != nil)
          @sort_type = params[:sort_type]
          @sort_dir = params[:sort_dir]
          if @sort_type == 'Person'
              @transactions_sorted = @transactions.sort_by { |transaction| transaction.requestor_name }
          elsif @sort_type == 'Item Name'
              @transactions_sorted = @transactions.sort_by { |transaction| [transaction.item_name] }
          elsif @sort_type == 'Item Amount'
              @transactions_sorted = @transactions.sort_by { |transaction| transaction.item_quantity }
          elsif @sort_type == 'Event'
              @transactions_sorted = @transactions.sort_by { |transaction| transaction.event }
          elsif @sort_type == 'Checkout Date'
              @transactions_sorted = @transactions.sort_by { |transaction| transaction.created_at }
            elsif @sort_type == 'Status'
              @transactions_sorted = @transactions.sort_by { |transaction| transaction.type_ }
          end

          if @sort_dir == 'Z -> A'
              @transactions_sorted = @transactions_sorted.reverse
          end
      else
          @sort_type = 'Checkout Date'
          @sort_dir = 'A -> Z'
          @transactions_sorted = @transactions
      end
    else
      @transactions = Transaction.sorted
      if ((params[:search_tag] != nil) && (params[:search_tag] != ""))
        @transactions_person = Transaction.where(requestor_name: params[:search_tag])
        @transactions_item = Transaction.where(item_name: params[:search_tag])
        @transactions_amount = Transaction.where(item_quantity: params[:search_tag])
        @transactions_event = Transaction.where(event: params[:search_tag])
        @transactions_created = Transaction.where(created_at: params[:search_tag])
        @transactions_status = Transaction.where(type_: params[:search_tag])
        @transactions_sorted = [].concat(@transactions_person)
                                  .concat(@transactions_item)
                                  .concat(@transactions_amount)
                                  .concat(@transactions_event)
                                  .concat(@transactions_created)
                                  .concat(@transactions_status)
        @transactions_sorted = @transactions_sorted.uniq
      elsif (params[:sort_type] != nil)
        @sort_type = params[:sort_type]
        @sort_dir = params[:sort_dir]
        if @sort_type == 'Person'
            @transactions_sorted = @transactions.sort_by { |transaction| transaction.requestor_name }
        elsif @sort_type == 'Item Name'
            @transactions_sorted = @transactions.sort_by { |transaction| [transaction.item_name] }
        elsif @sort_type == 'Item Amount'
            @transactions_sorted = @transactions.sort_by { |transaction| transaction.item_quantity }
        elsif @sort_type == 'Event'
            @transactions_sorted = @transactions.sort_by { |transaction| transaction.event }
        elsif @sort_type == 'Checkout Date'
            @transactions_sorted = @transactions.sort_by { |transaction| transaction.created_at }
          elsif @sort_type == 'Status'
            @transactions_sorted = @transactions.sort_by { |transaction| transaction.type_ }
        end

        if @sort_dir == 'Z -> A'
            @transactions_sorted = @transactions_sorted.reverse
        end
      else
          @sort_type = 'Checkout Date'
          @sort_dir = 'A -> Z'
          @transactions_sorted = @transactions
      end
    end
  end

  def show
    @transaction = Transaction.find(params[:id])
  end

  def new
    @transaction = Transaction.new
    #@log = Log.new
  end

#doesn't end up being used
  def create
    @transaction = Transaction.new(transaction_params) # need to find out how to set the 2 week immediately
    @transaction.type_ = 'Checked Out'
    remind_date = Time.now + (2 * 7 * 24 * 60 * 60) # get the time current time and set it to two weeks later
    @transaction.remind_date = remind_date # might need to format this
    # @transaction.user_id = session[:user_id]

    @log = Log.new
    @log.id = @transaction.id
    @log.requestor_name = @transaction.requestor_name
    @log.requestor_email = @transaction.requestor_email
    @log.type_ = @transaction.type_
    @log.item_name = @transaction.item_name
    @log.item_quantity = @transaction.item_quantity
    # @log.user_id = session[:user_id]

    if is_email_valid?(@transaction.requestor_email)
      if @transaction.save
        @log.save
        redirect_to(transactions_path)
      else
        render('new')
      end
    else
      flash[:notice] = 'Uh oh! The email that you entered is not a valid email address, try again!'
      render('new')
    end
  end

  # Update this to checkout items from database
  def checkout
    #emulate checkout/index
    @item = Item.find(params[:id])
  end

  def submit
    #emulate checkout/submit
    @item = Item.find(params[:id])
    @user = User.find(params[:uid])

    if (params[:checkout_amount].to_i > @item.avail_stock)
        flash[:notice] = "Sorry, there aren't enough items available to checkout"
        redirect_to({:controller => 'items', :action => 'index', :id => @item.id})
    else
      @item.avail_stock = @item.avail_stock-(params[:checkout_amount].to_i)
      if @item.merch == 'Yes'
          @item.total_stock = @item.total_stock - (params[:checkout_amount].to_i)
      end
      @item.save

      @user.item_ids.append(@item.id)
      @user.save

      @transaction = Transaction.new
      @transaction.user_id = @user.id
      @transaction.requestor_name = @user.first_name + " " + @user.last_name
      @transaction.requestor_email = @user.email
      @transaction.item_name = @item.name
      @transaction.item_quantity = params[:checkout_amount]
      @transaction.type_ = 'Checked Out'
      remind_date = Time.now + (2 * 7 * 24 * 60 * 60) # get the time current time and set it to two weeks later
      @transaction.remind_date = remind_date # might need to
      @transaction.event = params[:event]
      @transaction.save

      @log = Log.new
      @log.id = @transaction.id
      @log.requestor_name = @transaction.requestor_name
      @log.requestor_email = @transaction.requestor_email
      @log.type_ = @transaction.type_
      @log.item_name = @transaction.item_name
      @log.item_quantity = @transaction.item_quantity
      @log.event = @transaction.event

      @log.save

      redirect_to({:controller => 'items', :action => 'index'})
    end
  end

  # in this case, I am using edit/update as the "check in" form
  # Update this to re-enter Item into databse
  def edit
    @transaction = Transaction.find(params[:id])
  end

  def update
    @transaction = Transaction.find(params[:id])
    @log = Log.find(params[:id])
    @log.type_ = 'Checked In'
    time = Time.new
    @log.check_in = Date.new(time.year, time.month, time.day)
    @transaction.type_ = 'Checked In' # hopefully updates the 'type_' attribute in table

    # update to include items model

    @item = Item.find_by name: @transaction.item_name
    @item.avail_stock = @item.avail_stock+@transaction.item_quantity;
    if @item.merch == "Yes"
      @item.total_stock = @item.total_stock+@transaction.item_quantity;
      ## TODO: Create form to edit this value based on merch given away
    end
    @item.save;

    @user = User.find(@transaction.user_id)

    # TODO: Update to account for :return_amount in form
    @user.item_ids.delete(@item.id)
    @user.save

    if @transaction.save
      @log.save
      redirect_to(log_index_path)
    else
      render('edit')
    end
  end

  # these bottom two probably should never be used, but I included the definitions here just in case
  def delete; end

  def destroy; end

  # Create a function to view all items checked out by the user
  def showAllUserItems
      @transactions = Transaction.where(user_id: params[:id]).sorted
      @user = User.find(params[:id])
      if (params[:sort_type] != nil)
          @sort_type = params[:sort_type]
          @sort_dir = params[:sort_dir]
          if @sort_type == 'Item Name'
              @transactions_sorted = @transactions.sort_by { |transaction| transaction.item_name }
          elsif @sort_type == 'Person'
              @transactions_sorted = @transactions.sort_by { |transaction| [transaction.requestor_name] }
          elsif @sort_type == 'Checkout Date'

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/views/transactions/checkout.html.erb
<div class="top-button">
  <button type="button"><%= link_to("Back to Inventory Page", items_path, :class => 'back-link') %></button>
</div>

<div class = "container">
  <div class="row">
  <div class="col" align="center">
    <div class="Titles">
      Checkout Item
    </div>
  </div>
  </div>

  <%= form_tag({:action => 'submit', :id => @item.id, :uid => session[:user_id]}, :method => :post) do %>
    <table class="table" summary = "item details">
      <tr>
        <th>Name</th>
        <td><%= @item.name %></td>
      </tr>
      <tr>
        <th>Description</th>
        <td><%= @item.description %></td>
      </tr>
      <tr>
        <th>Total Stock</th>
        <td><%= @item.total_stock %></td>
      </tr>
      <tr>
        <th>Available Stock</th>
        <td><%= @item.avail_stock %></td>
      </tr>
      <tr>
        <th>Quantity</th>
        <td><%= text_field_tag(:checkout_amount) %></td>
      </tr>
      <tr>
        <th>Event</th>
        <td><%= text_field_tag(:event) %></td>
      </tr>
    </table>

    <div class="form-buttons" align="center">
    <%= submit_tag("Submit") %>
    </div>
  <% end %>
</div>

app/views/transactions/delete.html.erb
<% if current_user %>
      Logged in as <%= current_user.name %>
      <%= link_to "Log Out", session_path("current"), method: "delete" %>
    <% else %>
      <%= link_to "Sign Up", new_user_path %> or
      <%= link_to "Log In", new_session_path %>
    <% end %>
<h1>Transactions#delete</h1>
<p>Find me in app/views/transactions/delete.html.erb</p>

app/views/transactions/edit.html.erb
<div class="container-fluid">

  <button type="button"><%= link_to("Back to Transactions Page", transactions_path, :class => 'back-link') %></button>

  <div class="row">
    <div class="col" align="center">
      <div class="Titles">
        Check In Item
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col" align="center">
      <div class="card" style="margin-top:2%; width:50%; margin-left:0%;" align="center">
        <div class="card-body">
          <h1>Check In Item Confirmation Page!</h1>
          <%= form_for(@transaction) do |f| %>
          <p>Can you confirm that the item has been returned to its rightful place?</p>
          <div class="form-buttons">
            <%= f.submit("Submit") %>
           </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/transactions/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col" align="center">
      <div class="Titles">
        Check In/Out
      </div>
    </div>
  </div>

  <%= form_tag({:action => 'index'}, :method => :get) do %>
    <p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp

      Sort By: <%= select_tag "sort_type", options_for_select(['Person', 'Item Name',
      'Item Amount', 'Event', 'Checkout Date', 'Status'], @sort_type)%>
      <%= select_tag "sort_dir", options_for_select(['A -> Z', 'Z -> A'], @sort_dir)%>
      <%= submit_tag("Sort") %>

      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp

      <%= text_field_tag "search_tag"%>
      <%= submit_tag("Search") %></p>
  <% end %>

  <div class="row">
    <div class="col">
      <div class="card" style="margin-top:2%; width:100%; margin-left:0%;" align="center">
        <div class="card-body">
        <table class="listing" summary="Transaction List">
        <tr class="header">
            <th style="padding:0 15px 0 0;">Checked Out By</th>
            <th style="padding:0 15px 0 0;">Item</th>
            <th style="padding:0 15px 0 0;">Quantity</th>
            <th style="padding:0 15px 0 0;">Event</th>
            <th style="padding:0 15px 0 0;">Checkout date</th>
            <th style="padding:0 15px 0 0;">Status</th>
            <th style="padding:0 15px 0 0;">Details</th>
        </tr>
        <% @transactions_sorted.each do |t| %>
            <% if t.type_ == "Checked In" %>
                <% next %>
            <% end %>
        <tr class="tableEntries">
            <td style="padding:0 15px 0 0;"><%= t.requestor_name %></td>
            <td style="padding:0 15px 0 0;"><%= t.item_name %></td>
            <td style="padding:0 15px 0 0;"><%= t.item_quantity %></td>
            <td style="padding:0 15px 0 0;"><%= t.event %></td>
            <td style="padding:0 15px 0 0;"><%= t.created_at %></td>
            <td style="padding:0 15px 0 0;"><%= t.type_ %></td>
            <td class="actions" style="padding:0 15px 0 0;">
              <button type="button" ><%= link_to("View Details", transaction_path(t), :class => 'action show') %></button>
              <button type="button" ><%= link_to("Return", edit_transaction_path(t), :class => 'action edit') %></button>
            </td>
        </tr>
        <% end %>
    </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/transactions/show.html.erb
<div class = "top-button">
  <button type="button"><%= link_to("Back to Transactions Page", transactions_path, :class => 'back-link') %></button>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col" align="center">
      <div class="Titles">
         View Details
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col"align="center">
      <div class="card" style="margin-top:2%; width:50%; margin-left:0%;" align="center">
        <div class="card-body">
        <table summary="transaction Detail view">
          <tr class="tableEntries">
            <th>Check Out Person Name</th>
            <td style="padding:0 0 0 15px;"><%= @transaction.requestor_name %></td>
          </tr>
          <tr class="tableEntries">
            <th>Check Out Person Email</th>
            <td style="padding:0 0 0 15px;"><%= @transaction.requestor_email %></td>
          </tr>
          <tr class="tableEntries">
            <th>Item Checked Out</th>
            <td style="padding:0 0 0 15px;"><%= @transaction.item_name %></td>
          </tr>
          <tr class="tableEntries">
            <th>Quantity Checked Out</th>
            <td style="padding:0 0 0 15px;"><%= @transaction.item_quantity %></td>
          </tr>
          <tr class="tableEntries">
            <th>Event</th>
            <td style="padding:0 0 0 15px;"><%= @transaction.event %></td>
          </tr>
          <tr class="tableEntries">
            <th>Reminder To Return Date</th>
            <td style="padding:0 0 0 15px;"><%= @transaction.remind_date %></td>
          </tr>
          <tr class="tableEntries">
            <th>Checked Out On</th>
            <td style="padding:0 0 0 15px;"><%= @transaction.created_at %></td>
          </tr>
          <tr class="tableEntries">
            <th>Checked Out Status</th>
            <td style="padding:0 0 0 15px;"><%= @transaction.type_ %></td>
          </tr>
        </table>
        </div>
      </div>
    </div>
  </div>

app/views/transactions/showAllUserItems.html.erb
<div class= "top-button">
  <button type="button"><%= link_to("Back to Users Page", users_path, :class => 'back-link') %></button>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col" align="center">
      <div class="Titles">
        <%= @user.first_name %> <%= @user.last_name %>'s Items
      </div>
    </div>
  </div>

  <%= form_tag({:action => 'showAllUserItems'}, :method => :get) do %>
    <p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp

      Sort By: <%= select_tag "sort_type", options_for_select(['Person', 'Item Name',
      'Item Amount', 'Event', 'Checkout Date', 'Status'], @sort_type)%>
      <%= select_tag "sort_dir", options_for_select(['A -> Z', 'Z -> A'], @sort_dir)%>
      <%= submit_tag("Sort") %>

      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp

      <%= text_field_tag "search_tag"%>
      <%= hidden_field_tag "id", @user.id %>
      <%= submit_tag("Search") %></p>
  <% end %>

  <div class="row">
    <div class="col">
      <div class="card" style="margin-top:2%; width:100%; margin-left:0%;" align="center">
        <div class="card-body">
        <table class="listing" summary="Transaction List">
        <tr class="header">
            <th style="padding:0 15px 0 0;">Checked Out By</th>
            <th style="padding:0 15px 0 0;">Item</th>
            <th style="padding:0 15px 0 0;">Quantity</th>
            <th style="padding:0 15px 0 0;">Event</th>
            <th style="padding:0 15px 0 0;">Checkout date</th>
            <th style="padding:0 15px 0 0;">Status</th>
            <th style="padding:0 15px 0 0;">Details</th>
        </tr>
        <% @transactions_sorted.each do |t| %>
            <% if t.type_ == "Checked In" %>
                <% next %>
            <% end %>
        <tr class="tableEntries">
            <td style="padding:0 15px 0 0;"><%= t.requestor_name %></td>
            <td style="padding:0 15px 0 0;"><%= t.item_name %></td>
            <td style="padding:0 15px 0 0;"><%= t.item_quantity %></td>
            <td style="padding:0 15px 0 0;"><%= t.event %></td>
            <td style="padding:0 15px 0 0;"><%= t.created_at %></td>
            <td style="padding:0 15px 0 0;"><%= t.type_ %></td>
            <td class="actions" style="padding:0 15px 0 0;">
              <button type="button" ><%= link_to("View Details", transaction_path(t), :class => 'action show') %></button>
              <button type="button" ><%= link_to("Return", edit_transaction_path(t), :class => 'action edit') %></button>
            </td>
        </tr>
        <% end %>
    </table>
        </div>
      </div>
    </div>
  </div>
</div>